// Contenido del test: áreas, temas, habilidades, preguntas y carreras.
// Para cambiar el test alcanza con editar este archivo.

// ---------------------------------------------------------------------------
// Áreas de interés (modelo RIASEC de Holland)
// ---------------------------------------------------------------------------
const AREAS = {
  R: {
    name: "Realista",
    short: "Técnico-práctico",
    color: "#e0794c",
    description:
      "Te gusta hacer cosas concretas: trabajar con las manos, con herramientas, máquinas, la naturaleza o el cuerpo. Preferís ver el resultado de lo que hacés antes que quedarte en la teoría.",
  },
  I: {
    name: "Investigador",
    short: "Científico-analítico",
    color: "#3d8bd9",
    description:
      "Te mueve la curiosidad: querés entender por qué pasan las cosas, analizar información y resolver problemas difíciles usando la lógica.",
  },
  A: {
    name: "Artístico",
    short: "Creativo-expresivo",
    color: "#d64fa6",
    description:
      "Necesitás crear y expresarte. Te sentís bien en lugares con libertad, donde se valoran las ideas originales y no todo es rutina.",
  },
  S: {
    name: "Social",
    short: "Servicio a las personas",
    color: "#2fa776",
    description:
      "Disfrutás ayudar, enseñar, escuchar y acompañar. Te importa que tu trabajo le cambie algo para bien a otras personas.",
  },
  E: {
    name: "Emprendedor",
    short: "Liderazgo y negocios",
    color: "#e2a521",
    description:
      "Te gusta liderar, convencer, negociar y tomar decisiones. Te motivan los desafíos, los objetivos ambiciosos y mover proyectos para adelante.",
  },
  C: {
    name: "Convencional",
    short: "Organización y método",
    color: "#7a68d8",
    description:
      "Sos una persona ordenada, prolija y metódica. Te sentís cómoda/o con tareas claras, datos, números y procesos bien definidos.",
  },
};

// ---------------------------------------------------------------------------
// Temas (campos de interés) y habilidades
// ---------------------------------------------------------------------------
const FIELDS = {
  salud: "Salud y medicina",
  ciencia: "Ciencia e investigación",
  tecnologia: "Tecnología y computación",
  naturaleza: "Naturaleza, animales y medio ambiente",
  construccion: "Construcción, máquinas e ingeniería",
  arte: "Arte, diseño y moda",
  escena: "Música, teatro, cine y danza",
  comunicacion: "Comunicación, medios y redes",
  negocios: "Negocios, empresas y plata",
  sociedad: "Leyes, política y sociedad",
  educacion: "Educación y enseñanza",
  mente: "La mente y el comportamiento",
  deporte: "Deporte y actividad física",
  gastro: "Gastronomía, turismo y hotelería",
};

const SKILLS = {
  numeros: "los números y la matemática",
  escritura: "escribir y redactar",
  oratoria: "hablar en público y convencer",
  visual: "dibujar e imaginar cosas en el espacio",
  manual: "trabajar con las manos",
  ciencias: "biología, química y ciencias",
  compu: "la computadora y la tecnología",
  orden: "organizar y prestar atención al detalle",
  empatia: "escuchar y entender a otras personas",
  liderazgo: "liderar y tomar decisiones",
  idiomas: "los idiomas",
  fisico: "el deporte y lo físico",
  creatividad: "tener ideas originales",
};

// ---------------------------------------------------------------------------
// Partes del test
// ---------------------------------------------------------------------------
const SECTIONS = {
  inicio: { title: "Antes de empezar", subtitle: "Para darte información de dónde estudiar." },
  intereses: { title: "Lo que te gusta", subtitle: "Elegí la opción que más vaya con vos, aunque ninguna sea perfecta." },
  temas: { title: "Los temas que te atraen", subtitle: "Pensá en qué cosas te generan curiosidad." },
  habilidades: { title: "Lo que te sale bien", subtitle: "Sé honesta/o: no hace falta ser experta/o, alcanza con que te salga más fácil que otras cosas." },
  preferencias: { title: "Cómo te imaginás estudiando y trabajando", subtitle: "Esto sirve para filtrar las carreras que no van con tu vida." },
};

// ---------------------------------------------------------------------------
// Preguntas
//   type "single": se elige una opción.   type "multi": se eligen varias (hasta "max").
//   En cada opción: r = área RIASEC, f = temas, s = habilidades, v = valor de preferencia.
// ---------------------------------------------------------------------------
const QUESTIONS = [
  // --- Inicio ---
  {
    id: "pais", section: "inicio", type: "single", pref: "pais", keepOrder: true,
    text: "¿Dónde vas a estudiar?",
    options: [
      { label: "En Uruguay", v: "uy" },
      { label: "En Argentina", v: "ar" },
      { label: "En otro país", v: "otro" },
    ],
  },

  // --- Intereses (RIASEC) ---
  {
    id: "i1", section: "intereses", type: "single",
    text: "Tenés un sábado libre. ¿Qué preferís hacer?",
    options: [
      { label: "Arreglar algo de la casa o armar un mueble", r: "R" },
      { label: "Mirar documentales o investigar un tema que me intriga", r: "I" },
      { label: "Dibujar, escribir, sacar fotos o hacer música", r: "A" },
      { label: "Juntarme con amigos o hacer un voluntariado", r: "S" },
    ],
  },
  {
    id: "i2", section: "intereses", type: "single",
    text: "En un trabajo en grupo, ¿qué rol solés tomar?",
    options: [
      { label: "Lidero y reparto las tareas", r: "E" },
      { label: "Organizo el cronograma y reviso que todo esté completo", r: "C" },
      { label: "Me encargo del diseño y la presentación", r: "A" },
      { label: "Me aseguro de que todos se lleven bien y participen", r: "S" },
    ],
  },
  {
    id: "i3", section: "intereses", type: "single",
    text: "¿Cuál de estas materias te gusta (o te gustaba) más?",
    options: [
      { label: "Biología, química o física", r: "I" },
      { label: "Matemática o contabilidad", r: "C" },
      { label: "Arte, música o literatura", r: "A" },
      { label: "Tecnología, taller o educación física", r: "R" },
    ],
  },
  {
    id: "i4", section: "intereses", type: "single",
    text: "¿Qué te gustaría que digan de vos?",
    options: [
      { label: "Que sos una persona empática y que sabe escuchar", r: "S" },
      { label: "Que sos convincente y vas por tus metas", r: "E" },
      { label: "Que sos curiosa/o e inteligente", r: "I" },
      { label: "Que sos muy hábil con las manos", r: "R" },
    ],
  },
  {
    id: "i5", section: "intereses", type: "single",
    text: "¿Cómo sería tu lugar de trabajo ideal?",
    options: [
      { label: "Al aire libre, en un taller o en una obra", r: "R" },
      { label: "Una oficina ordenada, con tareas claras", r: "C" },
      { label: "Un estudio creativo, sin horarios rígidos", r: "A" },
      { label: "Moviéndome, en reuniones y viajando", r: "E" },
    ],
  },
  {
    id: "i6", section: "intereses", type: "single",
    text: "Frente a un problema complicado, ¿qué hacés primero?",
    options: [
      { label: "Busco información y analizo los datos", r: "I" },
      { label: "Lo charlo con otras personas para escuchar opiniones", r: "S" },
      { label: "Sigo un método paso a paso", r: "C" },
      { label: "Tomo una decisión rápido y me pongo en acción", r: "E" },
    ],
  },
  {
    id: "i7", section: "intereses", type: "single",
    text: "Si pudieras crear una app, ¿de qué sería?",
    options: [
      { label: "Una red para que artistas muestren sus obras", r: "A" },
      { label: "Una que use datos para predecir enfermedades o el clima", r: "I" },
      { label: "Una para acompañar la salud mental de las personas", r: "S" },
      { label: "Una para controlar robots o la casa a distancia", r: "R" },
    ],
  },
  {
    id: "i8", section: "intereses", type: "single",
    text: "¿Qué tipo de libro, serie o podcast elegís?",
    options: [
      { label: "Ciencia, misterios del universo o del cuerpo humano", r: "I" },
      { label: "Fantasía, arte o historias muy creativas", r: "A" },
      { label: "Biografías de emprendedores y líderes", r: "E" },
      { label: "Economía, finanzas o cómo funcionan las empresas", r: "C" },
    ],
  },
  {
    id: "i9", section: "intereses", type: "single",
    text: "Te sumás a un voluntariado. ¿Qué tarea elegís?",
    options: [
      { label: "Dar clases de apoyo a chicos", r: "S" },
      { label: "Construir o reparar viviendas", r: "R" },
      { label: "Llevar el registro de donaciones y el inventario", r: "C" },
      { label: "Conseguir sponsors y difundir la campaña", r: "E" },
    ],
  },
  {
    id: "i10", section: "intereses", type: "single",
    text: "¿Qué es lo que más disfrutás?",
    options: [
      { label: "Expresar ideas de forma original", r: "A" },
      { label: "Entender por qué pasan las cosas", r: "I" },
      { label: "Ver el resultado concreto de lo que hice", r: "R" },
      { label: "Que todo quede en orden y sin errores", r: "C" },
    ],
  },
  {
    id: "i11", section: "intereses", type: "single",
    text: "Si ganaras un premio, ¿cuál te gustaría que fuera?",
    options: [
      { label: "Mejor emprendimiento del año", r: "E" },
      { label: "Reconocimiento por ayudar a mi comunidad", r: "S" },
      { label: "Un premio científico por un descubrimiento", r: "I" },
      { label: "Un premio en un festival de cine, arte o música", r: "A" },
    ],
  },
  {
    id: "i12", section: "intereses", type: "single",
    text: "¿Con qué herramienta te sentís más cómoda/o?",
    options: [
      { label: "Una caja de herramientas", r: "R" },
      { label: "Una planilla de cálculo", r: "C" },
      { label: "Un microscopio o un telescopio", r: "I" },
      { label: "Una cámara, pinceles o una guitarra", r: "A" },
    ],
  },
  {
    id: "i13", section: "intereses", type: "single",
    text: "¿Qué es lo que más te frustra?",
    options: [
      { label: "El desorden y la improvisación", r: "C" },
      { label: "No poder tomar las decisiones", r: "E" },
      { label: "Ver a alguien mal y no poder ayudar", r: "S" },
      { label: "Estar quieta/o todo el día frente a una pantalla", r: "R" },
    ],
  },
  {
    id: "i14", section: "intereses", type: "single",
    text: "¿A qué charla irías?",
    options: [
      { label: "Avances en medicina e inteligencia artificial", r: "I" },
      { label: "Cómo negociar y vender cualquier idea", r: "E" },
      { label: "Cómo despertar tu creatividad", r: "A" },
      { label: "Educación y psicología para ayudar a otros", r: "S" },
    ],
  },
  {
    id: "i15", section: "intereses", type: "single",
    text: "¿Cómo te imaginás en 10 años?",
    options: [
      { label: "Trabajando con máquinas, la naturaleza o el deporte", r: "R" },
      { label: "Con un trabajo estable, claro y bien pago", r: "C" },
      { label: "Al frente de mi propio emprendimiento", r: "E" },
      { label: "Trabajando con personas y cambiándoles la vida", r: "S" },
    ],
  },
  {
    id: "i16", section: "intereses", type: "single",
    text: "¿Qué video mirás hasta el final?",
    options: [
      { label: "Cómo se construye un puente o se arma un motor", r: "R" },
      { label: "Un experimento científico", r: "I" },
      { label: "El proceso de un artista haciendo una obra", r: "A" },
      { label: "Cómo organizar tu plata y tus gastos del mes", r: "C" },
    ],
  },
  {
    id: "i17", section: "intereses", type: "single",
    text: "Una amiga o amigo tiene un problema. ¿Cómo lo ayudás?",
    options: [
      { label: "Lo escucho y lo acompaño", r: "S" },
      { label: "Le armo un plan y lo motivo para que actúe", r: "E" },
      { label: "Si es algo práctico, voy y se lo arreglo", r: "R" },
      { label: "Investigo el tema para darle la mejor información", r: "I" },
    ],
  },
  {
    id: "i18", section: "intereses", type: "single",
    text: "Te ofrecen un trabajo de verano. ¿Cuál elegís?",
    options: [
      { label: "Decorar vidrieras o hacer contenido para redes", r: "A" },
      { label: "Atender la caja y llevar las cuentas de un local", r: "C" },
      { label: "Animar actividades en una colonia de vacaciones", r: "S" },
      { label: "Vender un producto y ganar comisión", r: "E" },
    ],
  },

  // --- Temas ---
  {
    id: "t1", section: "temas", type: "multi", max: 4, keepOrder: true,
    text: "¿Qué temas te atraen? Elegí hasta 4.",
    options: Object.entries(FIELDS).map(([key, label]) => ({ label, f: [key] })),
  },
  {
    id: "t2", section: "temas", type: "single",
    text: "¿Qué problema del mundo te gustaría ayudar a resolver?",
    options: [
      { label: "Curar enfermedades y que la gente viva mejor", f: ["salud"] },
      { label: "El cambio climático y el cuidado de los animales", f: ["naturaleza"] },
      { label: "La injusticia y la desigualdad", f: ["sociedad"] },
      { label: "Que todos los chicos reciban buena educación", f: ["educacion"] },
    ],
  },
  {
    id: "t3", section: "temas", type: "single",
    text: "Entrás a una librería. ¿A qué sección vas?",
    options: [
      { label: "Ciencia y divulgación", f: ["ciencia"] },
      { label: "Arte, diseño y moda", f: ["arte"] },
      { label: "Negocios y finanzas", f: ["negocios"] },
      { label: "Psicología", f: ["mente"] },
    ],
  },
  {
    id: "t4", section: "temas", type: "single",
    text: "¿Qué cuentas seguís más en redes?",
    options: [
      { label: "Tecnología, gadgets o gaming", f: ["tecnologia"] },
      { label: "Recetas, restaurantes y viajes", f: ["gastro"] },
      { label: "Música, actores o cine", f: ["escena"] },
      { label: "Deportistas o fitness", f: ["deporte"] },
    ],
  },
  {
    id: "t5", section: "temas", type: "single",
    text: "Podés visitar un lugar de trabajo por un día. ¿Cuál elegís?",
    options: [
      { label: "Una obra en construcción o una fábrica", f: ["construccion"] },
      { label: "Un canal de TV o una agencia de publicidad", f: ["comunicacion"] },
      { label: "Un hospital", f: ["salud"] },
      { label: "Un juzgado o el Parlamento", f: ["sociedad"] },
    ],
  },
  {
    id: "t6", section: "temas", type: "single",
    text: "¿Qué documental mirarías esta noche?",
    options: [
      { label: "Cómo funciona el cerebro humano", f: ["mente"] },
      { label: "Animales salvajes y ecosistemas", f: ["naturaleza"] },
      { label: "Cómo se hizo un videojuego famoso", f: ["tecnologia"] },
      { label: "La historia de una marca famosa", f: ["negocios"] },
    ],
  },

  // --- Habilidades ---
  {
    id: "h1", section: "habilidades", type: "multi", max: 3, keepOrder: true,
    text: "¿En qué materias te iba mejor? Elegí hasta 3.",
    options: [
      { label: "Matemática", s: ["numeros"] },
      { label: "Física", s: ["numeros", "ciencias"], f: ["ciencia"] },
      { label: "Biología o química", s: ["ciencias"], f: ["ciencia", "salud"] },
      { label: "Idioma español / Literatura", s: ["escritura"], f: ["comunicacion"] },
      { label: "Historia, geografía o sociales", s: ["escritura"], f: ["sociedad"] },
      { label: "Inglés u otros idiomas", s: ["idiomas"] },
      { label: "Dibujo o artes plásticas", s: ["visual", "creatividad"], f: ["arte"] },
      { label: "Informática", s: ["compu"], f: ["tecnologia"] },
      { label: "Educación física", s: ["fisico"], f: ["deporte"] },
      { label: "Música", s: ["creatividad"], f: ["escena"] },
      { label: "Contabilidad o economía", s: ["numeros", "orden"], f: ["negocios"] },
      { label: "Filosofía o psicología", s: ["empatia", "escritura"], f: ["mente"] },
    ],
  },
  {
    id: "h2", section: "habilidades", type: "multi", max: 5, keepOrder: true,
    text: "¿Qué cosas te salen bien? Elegí hasta 5.",
    options: Object.entries(SKILLS).map(([key, label]) => ({
      label: label.charAt(0).toUpperCase() + label.slice(1),
      s: [key],
    })),
  },
  {
    id: "h3", section: "habilidades", type: "single",
    text: "Tus amigos te piden ayuda para...",
    options: [
      { label: "Entender un ejercicio de matemática", s: ["numeros"] },
      { label: "Contarte un problema y que los escuches", s: ["empatia"] },
      { label: "Arreglar el celular o la compu", s: ["compu"] },
      { label: "Editar fotos o elegir qué ponerse", s: ["visual", "creatividad"] },
    ],
  },
  {
    id: "h4", section: "habilidades", type: "single",
    text: "En un trabajo grupal, lo que mejor te sale es...",
    options: [
      { label: "Exponer frente a la clase", s: ["oratoria"] },
      { label: "Redactar el texto", s: ["escritura"] },
      { label: "Organizar las fechas y las tareas", s: ["orden"] },
      { label: "Coordinar al grupo y decidir", s: ["liderazgo"] },
    ],
  },
  {
    id: "h5", section: "habilidades", type: "single",
    text: "¿Qué te sale más fácil?",
    options: [
      { label: "Armar o reparar cosas", s: ["manual"] },
      { label: "Aprender palabras de otro idioma", s: ["idiomas"] },
      { label: "Hacer deporte o actividad física", s: ["fisico"] },
      { label: "Inventar ideas nuevas", s: ["creatividad"] },
    ],
  },

  // --- Preferencias ---
  {
    id: "p1", section: "preferencias", type: "single", pref: "dur", keepOrder: true,
    text: "¿Cuánto tiempo estás dispuesta/o a estudiar?",
    options: [
      { label: "Algo corto (1 o 2 años) para trabajar pronto", v: 2 },
      { label: "Una carrera de 3 o 4 años", v: 4 },
      { label: "5 años o más, si es lo que me gusta", v: 99 },
      { label: "Todavía no sé", v: 99 },
    ],
  },
  {
    id: "p2", section: "preferencias", type: "single", pref: "math", keepOrder: true,
    text: "¿Cómo te llevás con la matemática?",
    options: [
      { label: "Me encanta", v: 3 },
      { label: "La banco, me va bien", v: 2 },
      { label: "Prefiero que haya poca", v: 1 },
      { label: "La evito todo lo posible", v: 0 },
    ],
  },
  {
    id: "p3", section: "preferencias", type: "single", pref: "sangre", keepOrder: true,
    text: "¿Cómo te llevás con la sangre, las agujas o los hospitales?",
    options: [
      { label: "Sin problema", v: 0 },
      { label: "Me impresiona un poco, pero me acostumbraría", v: 1 },
      { label: "Me impresiona mucho, no podría", v: 2 },
    ],
  },
  {
    id: "p4", section: "preferencias", type: "single", pref: "gente", keepOrder: true,
    text: "¿Cuánto contacto con gente querés en tu trabajo?",
    options: [
      { label: "Mucho, todo el día", v: 2 },
      { label: "Algo, en equilibrio", v: 1 },
      { label: "Poco, prefiero concentrarme en lo mío", v: 0 },
    ],
  },
  {
    id: "p5", section: "preferencias", type: "single", pref: "env", keepOrder: true,
    text: "¿Dónde te gustaría pasar tu día de trabajo?",
    options: [
      { label: "En una oficina o desde casa con la compu", v: "oficina" },
      { label: "Al aire libre o moviéndome", v: "aire" },
      { label: "En un hospital, clínica o consultorio", v: "clinica" },
      { label: "En un taller, estudio o laboratorio", v: "taller" },
      { label: "En una escuela, liceo o con grupos", v: "aula" },
    ],
  },
  {
    id: "p6", section: "preferencias", type: "single", pref: "prio", keepOrder: true,
    text: "¿Qué es lo más importante para vos en un trabajo?",
    options: [
      { label: "Ganar bien", v: "plata" },
      { label: "Tener estabilidad y conseguir trabajo fácil", v: "estable" },
      { label: "Hacer algo que me apasione", v: "pasion" },
      { label: "Ayudar a otras personas", v: "ayudar" },
    ],
  },
];

// ---------------------------------------------------------------------------
// Carreras
//   code: código RIASEC (la primera letra es la que más pesa)
//   durNum: años aproximados   math: 0 nada · 1 poca · 2 media · 3 mucha
//   people: 0 poco · 1 algo · 2 mucho contacto con gente   sangre: contacto con sangre o procedimientos
//   env: dónde se trabaja   demand: salida laboral 0 competida · 1 media · 2 alta
// ---------------------------------------------------------------------------
const CAREERS = [
  // ===== Salud =====
  {
    id: "medicina", name: "Medicina", code: "ISR",
    fields: ["salud", "ciencia"], skills: ["ciencias", "empatia", "orden"],
    dur: "7 años + residencia (especialidad)", durNum: 7, type: "Universitaria",
    math: 2, people: 2, sangre: true, env: ["clinica"], demand: 2,
    desc: "Diagnosticás y tratás enfermedades. Después de recibirte elegís una especialidad: pediatría, cirugía, dermatología, psiquiatría, ginecología…",
    dia: "Atender pacientes en consultorio o en guardia, pedir y leer estudios, decidir tratamientos y seguir estudiando toda la vida.",
    materias: ["Anatomía", "Biología celular", "Fisiología", "Farmacología", "Clínica médica"],
    salida: "Muy buena: hay trabajo en todo el país, aunque los primeros años incluyen guardias largas.",
    ojo: "Es de las carreras más largas y exigentes: mucha memoria, guardias y responsabilidad.",
    uy: "UdelaR – Facultad de Medicina (pública y gratuita); CLAEH (privada, Punta del Este).",
    ar: "Universidades nacionales como UBA, UNLP, UNC o UNR (gratuitas) y privadas.",
  },
  {
    id: "enfermeria", name: "Licenciatura en Enfermería", code: "SIR",
    fields: ["salud"], skills: ["empatia", "ciencias", "fisico"],
    dur: "4 a 5 años", durNum: 4, type: "Universitaria",
    math: 1, people: 2, sangre: true, env: ["clinica"], demand: 2,
    desc: "Cuidás a pacientes de forma directa: sos quien más tiempo pasa con ellos en hospitales, emergencias, escuelas o domicilios.",
    dia: "Controlar signos vitales, dar medicación, hacer curaciones, acompañar a pacientes y familias y coordinar con los médicos.",
    materias: ["Enfermería comunitaria", "Anatomía", "Farmacología", "Salud mental", "Cuidados críticos"],
    salida: "Excelente: falta personal de enfermería en casi todos lados.",
    ojo: "Se trabaja por turnos (noches y fines de semana) y es emocionalmente intenso.",
    uy: "UdelaR – Facultad de Enfermería; UCU (privada).",
    ar: "Universidades nacionales y escuelas de enfermería terciarias en todas las provincias.",
  },
  {
    id: "odontologia", name: "Odontología", code: "IRS",
    fields: ["salud"], skills: ["manual", "ciencias", "orden"],
    dur: "5 años", durNum: 5, type: "Universitaria",
    math: 1, people: 2, sangre: true, env: ["clinica"], demand: 1,
    desc: "Prevenís y tratás problemas de dientes y boca. Es una carrera de salud muy manual y de mucha precisión.",
    dia: "Atender pacientes en consultorio: limpiezas, arreglos, extracciones, ortodoncia o estética dental.",
    materias: ["Anatomía", "Materiales dentales", "Operatoria", "Cirugía", "Ortodoncia"],
    salida: "Buena, sobre todo con consultorio propio o con una especialidad.",
    ojo: "Los materiales y el instrumental suelen ser caros durante la carrera.",
    uy: "UdelaR – Facultad de Odontología; UCU (privada).",
    ar: "UBA, UNLP, UNC y otras nacionales; también privadas.",
  },
  {
    id: "psicologia", name: "Psicología", code: "SIA",
    fields: ["mente", "salud"], skills: ["empatia", "escritura", "oratoria"],
    dur: "4 a 6 años", durNum: 5, type: "Universitaria",
    math: 1, people: 2, sangre: false, env: ["clinica", "oficina"], demand: 1,
    desc: "Estudiás cómo pensamos, sentimos y actuamos, y acompañás a personas a atravesar problemas emocionales.",
    dia: "Atender pacientes en sesiones, o trabajar en escuelas, empresas (selección de personal), hospitales o investigación.",
    materias: ["Psicología evolutiva", "Neurociencias", "Psicopatología", "Teorías de la personalidad", "Estadística"],
    salida: "Hay mucha gente recibida: le va mejor a quien se especializa (clínica, laboral, educacional, infantil).",
    ojo: "Hay muchísima lectura y escritura; para atender en clínica conviene hacer un posgrado.",
    uy: "UdelaR – Facultad de Psicología; UCU (privada).",
    ar: "UBA, UNLP, UNC, UNR y muchas privadas.",
  },
  {
    id: "nutricion", name: "Nutrición", code: "ISC",
    fields: ["salud", "gastro"], skills: ["ciencias", "empatia", "orden"],
    dur: "4 a 5 años", durNum: 4, type: "Universitaria",
    math: 2, people: 2, sangre: false, env: ["clinica", "oficina"], demand: 1,
    desc: "Diseñás planes de alimentación para cuidar la salud, tratar enfermedades o mejorar el rendimiento deportivo.",
    dia: "Consultas con pacientes, armar planes alimentarios, trabajar en hospitales, clubes deportivos, comedores o la industria alimentaria.",
    materias: ["Química", "Bioquímica", "Fisiología", "Nutrición clínica", "Técnica dietética"],
    salida: "Buena y en crecimiento, especialmente en nutrición deportiva y clínica.",
    ojo: "Tiene bastante química y bioquímica en los primeros años.",
    uy: "UdelaR – Escuela de Nutrición; UCU (privada).",
    ar: "UBA (Facultad de Medicina) y otras nacionales; también privadas.",
  },
  {
    id: "kinesiologia", name: "Fisioterapia / Kinesiología", code: "SRI",
    fields: ["salud", "deporte"], skills: ["fisico", "empatia", "manual", "ciencias"],
    dur: "4 a 5 años", durNum: 4, type: "Universitaria",
    math: 1, people: 2, sangre: false, env: ["clinica", "aire"], demand: 2,
    desc: "Ayudás a personas a recuperar el movimiento después de lesiones, cirugías o enfermedades, con ejercicios y técnicas manuales.",
    dia: "Sesiones de rehabilitación en clínicas, clubes deportivos, residenciales de adultos mayores o a domicilio.",
    materias: ["Anatomía", "Biomecánica", "Fisiología del ejercicio", "Técnicas kinésicas", "Neurología"],
    salida: "Muy buena; el área deportiva y la de adultos mayores crecen mucho.",
    ojo: "Es un trabajo físico y de mucho contacto con el cuerpo de otras personas.",
    uy: "UdelaR – Escuela Universitaria de Tecnología Médica (Fisioterapia); UCU (privada).",
    ar: "UBA, UNLP y otras nacionales (Kinesiología y Fisiatría); también privadas.",
  },
  {
    id: "fonoaudiologia", name: "Fonoaudiología", code: "SIA",
    fields: ["salud", "educacion", "mente"], skills: ["empatia", "oratoria"],
    dur: "4 años", durNum: 4, type: "Universitaria",
    math: 1, people: 2, sangre: false, env: ["clinica", "aula"], demand: 1,
    desc: "Tratás problemas de la voz, el habla, el lenguaje, la audición y la deglución, en niños y adultos.",
    dia: "Sesiones con niños que tardan en hablar, adultos que tuvieron un ACV, cantantes o docentes con problemas de voz.",
    materias: ["Anatomía de la voz", "Lingüística", "Audiología", "Desarrollo del lenguaje", "Neurología"],
    salida: "Buena, sobre todo en el área infantil.",
    ojo: "Requiere mucha paciencia: los avances suelen ser lentos.",
    uy: "UdelaR – Escuela Universitaria de Tecnología Médica.",
    ar: "UBA, UNC, UNR y otras nacionales; también privadas.",
  },
  {
    id: "farmacia", name: "Química Farmacéutica / Farmacia", code: "ICR",
    fields: ["salud", "ciencia"], skills: ["ciencias", "numeros", "orden"],
    dur: "5 años", durNum: 5, type: "Universitaria",
    math: 3, people: 1, sangre: false, env: ["taller", "clinica"], demand: 1,
    desc: "Te especializás en los medicamentos: cómo se fabrican, cómo actúan y cómo se usan de forma segura.",
    dia: "Trabajar en farmacias, hospitales, laboratorios de la industria farmacéutica o en control de calidad.",
    materias: ["Química general y orgánica", "Farmacología", "Bioquímica", "Tecnología farmacéutica", "Matemática"],
    salida: "Buena: la industria, los hospitales y las farmacias necesitan profesionales.",
    ojo: "Muchísima química y matemática; es exigente.",
    uy: "UdelaR – Facultad de Química (Química Farmacéutica).",
    ar: "UBA (Facultad de Farmacia y Bioquímica), UNLP, UNC y otras.",
  },
  {
    id: "veterinaria", name: "Veterinaria", code: "IRS",
    fields: ["naturaleza", "salud"], skills: ["ciencias", "manual", "empatia"],
    dur: "5 a 6 años", durNum: 5, type: "Universitaria",
    math: 2, people: 1, sangre: true, env: ["clinica", "aire"], demand: 1,
    desc: "Cuidás la salud de animales (mascotas, animales de campo o fauna silvestre) y controlás alimentos de origen animal.",
    dia: "Atender en una clínica de mascotas, recorrer establecimientos rurales, trabajar en frigoríficos o en investigación.",
    materias: ["Anatomía animal", "Fisiología", "Microbiología", "Clínica de pequeños y grandes animales", "Producción animal"],
    salida: "Buena, especialmente en el campo y la producción animal; la clínica de mascotas es más competida.",
    ojo: "Incluye cirugías, eutanasias y trabajo con animales de campo, no solo mascotas.",
    uy: "UdelaR – Facultad de Veterinaria.",
    ar: "UBA, UNLP, UNC, UNR y otras nacionales.",
  },
  {
    id: "obstetricia", name: "Obstetricia (Partera/o)", code: "SIR",
    fields: ["salud"], skills: ["empatia", "ciencias", "fisico"],
    dur: "4 a 5 años", durNum: 4, type: "Universitaria",
    math: 1, people: 2, sangre: true, env: ["clinica"], demand: 2,
    desc: "Acompañás el embarazo, el parto y el posparto, y trabajás en salud sexual y reproductiva.",
    dia: "Controles de embarazo, atención de partos, talleres de preparación y consejería en anticoncepción.",
    materias: ["Anatomía", "Obstetricia", "Neonatología", "Salud sexual y reproductiva", "Farmacología"],
    salida: "Muy buena; hay pocos profesionales y mucha demanda.",
    ojo: "Guardias largas y situaciones de mucha tensión.",
    uy: "UdelaR – Escuela de Parteras (Facultad de Medicina).",
    ar: "UBA (Licenciatura en Obstetricia) y otras nacionales.",
  },
  {
    id: "terapiaocupacional", name: "Terapia ocupacional", code: "SRA",
    fields: ["salud", "mente"], skills: ["empatia", "creatividad", "manual"],
    dur: "4 años", durNum: 4, type: "Universitaria",
    math: 0, people: 2, sangre: false, env: ["clinica", "aula"], demand: 1,
    desc: "Ayudás a personas con discapacidad, lesiones o problemas de salud mental a ser lo más independientes posible en su vida diaria.",
    dia: "Adaptar actividades y espacios, trabajar con niños con dificultades del desarrollo, adultos mayores o pacientes en rehabilitación.",
    materias: ["Anatomía", "Psicología", "Desarrollo infantil", "Rehabilitación", "Actividades terapéuticas"],
    salida: "Buena, y con pocos profesionales en el mercado.",
    ojo: "Es poco conocida, así que a veces vas a tener que explicar qué hacés.",
    uy: "UdelaR – Escuela Universitaria de Tecnología Médica.",
    ar: "UBA, UNMdP, UNL y otras nacionales.",
  },
  {
    id: "imagenologia", name: "Imagenología / Radiología (técnica)", code: "RIC",
    fields: ["salud", "tecnologia"], skills: ["ciencias", "compu", "orden"],
    dur: "3 a 4 años", durNum: 3, type: "Tecnicatura / licenciatura",
    math: 1, people: 1, sangre: false, env: ["clinica"], demand: 2,
    desc: "Manejás los equipos de radiografía, tomografía, resonancia y ecografía para obtener las imágenes que usan los médicos.",
    dia: "Preparar al paciente, operar equipos de alta tecnología y cuidar la calidad de las imágenes y la protección contra la radiación.",
    materias: ["Física de las radiaciones", "Anatomía", "Técnicas radiológicas", "Radioprotección"],
    salida: "Muy buena; hospitales y clínicas necesitan técnicos.",
    ojo: "Hay turnos rotativos y contacto con pacientes delicados.",
    uy: "UdelaR – Escuela Universitaria de Tecnología Médica (Imagenología).",
    ar: "Tecnicaturas y licenciaturas en universidades nacionales y terciarios de salud.",
  },
  {
    id: "laboratorio", name: "Laboratorio clínico", code: "ICR",
    fields: ["salud", "ciencia"], skills: ["ciencias", "orden"],
    dur: "3 a 4 años", durNum: 3, type: "Tecnicatura / licenciatura",
    math: 2, people: 0, sangre: true, env: ["taller", "clinica"], demand: 1,
    desc: "Analizás muestras de sangre, orina y otros fluidos para ayudar a diagnosticar enfermedades.",
    dia: "Trabajar con microscopios y equipos automatizados, procesar muestras y validar resultados.",
    materias: ["Química", "Hematología", "Microbiología", "Inmunología", "Control de calidad"],
    salida: "Buena en hospitales, mutualistas y laboratorios privados.",
    ojo: "Trabajo muy detallista y con poco contacto con pacientes.",
    uy: "UdelaR – Escuela Universitaria de Tecnología Médica (Laboratorio Clínico).",
    ar: "Universidades nacionales (Bioquímica o tecnicaturas en laboratorio) y terciarios.",
  },
  {
    id: "auxenfermeria", name: "Auxiliar de enfermería", code: "SRC",
    fields: ["salud"], skills: ["empatia", "fisico", "orden"],
    dur: "1 año aprox.", durNum: 1, type: "Curso",
    math: 0, people: 2, sangre: true, env: ["clinica"], demand: 2,
    desc: "Asistís al equipo de salud en el cuidado básico de pacientes. Es una forma rápida de entrar a trabajar en salud.",
    dia: "Higiene y confort de los pacientes, controles básicos y ayuda en tratamientos.",
    materias: ["Enfermería básica", "Primeros auxilios", "Anatomía", "Higiene"],
    salida: "Muy buena y rápida.",
    ojo: "Trabajo físico y por turnos; después podés seguir la licenciatura.",
    uy: "Escuelas habilitadas por el Ministerio de Salud Pública (MSP).",
    ar: "Escuelas e institutos habilitados por el Ministerio de Salud de cada provincia.",
  },

  // ===== Ciencias =====
  {
    id: "biologia", name: "Biología", code: "IRC",
    fields: ["ciencia", "naturaleza"], skills: ["ciencias", "numeros", "orden"],
    dur: "4 a 5 años", durNum: 4, type: "Universitaria",
    math: 2, people: 0, sangre: false, env: ["taller", "aire"], demand: 0,
    desc: "Estudiás los seres vivos: desde las células y los genes hasta los ecosistemas.",
    dia: "Investigar en el laboratorio o en el campo, hacer experimentos, escribir informes, trabajar en conservación o enseñar.",
    materias: ["Biología celular", "Genética", "Ecología", "Química", "Estadística"],
    salida: "Media: muchas salidas pasan por la investigación (con becas) o la docencia.",
    ojo: "Para investigar casi siempre hace falta maestría o doctorado.",
    uy: "UdelaR – Facultad de Ciencias (Licenciatura en Ciencias Biológicas).",
    ar: "UBA (Exactas), UNLP, UNC y otras nacionales.",
  },
  {
    id: "biotecnologia", name: "Bioquímica / Biotecnología", code: "IRC",
    fields: ["ciencia", "salud", "tecnologia"], skills: ["ciencias", "numeros", "compu"],
    dur: "4 a 5 años", durNum: 5, type: "Universitaria",
    math: 3, people: 0, sangre: false, env: ["taller"], demand: 1,
    desc: "Usás la biología y la química para crear soluciones: medicamentos, vacunas, alimentos, diagnósticos.",
    dia: "Trabajar en laboratorios de investigación, en la industria farmacéutica o alimentaria, o en empresas de biotecnología.",
    materias: ["Química orgánica", "Bioquímica", "Genética", "Microbiología", "Biología molecular"],
    salida: "Buena y en crecimiento, sobre todo en la industria.",
    ojo: "Muy exigente en química y matemática.",
    uy: "UdelaR – Facultad de Ciencias (Bioquímica); ORT (Biotecnología, privada).",
    ar: "UBA (Bioquímica), UNQ y UNSAM (Biotecnología), UNL y otras.",
  },
  {
    id: "quimica", name: "Química", code: "IRC",
    fields: ["ciencia"], skills: ["ciencias", "numeros", "orden"],
    dur: "5 años", durNum: 5, type: "Universitaria",
    math: 3, people: 0, sangre: false, env: ["taller"], demand: 1,
    desc: "Estudiás la materia y sus transformaciones, y diseñás y controlás procesos y productos químicos.",
    dia: "Trabajo de laboratorio, control de calidad en industrias, análisis ambientales y desarrollo de productos.",
    materias: ["Química general, orgánica e inorgánica", "Química analítica", "Fisicoquímica", "Matemática"],
    salida: "Buena en la industria y en control de calidad.",
    ojo: "Mucha matemática y física.",
    uy: "UdelaR – Facultad de Química.",
    ar: "UBA (Exactas), UNLP, UNC y otras.",
  },
  {
    id: "fisicamat", name: "Física / Matemática", code: "ICA",
    fields: ["ciencia"], skills: ["numeros", "orden", "creatividad"],
    dur: "4 a 5 años", durNum: 5, type: "Universitaria",
    math: 3, people: 0, sangre: false, env: ["oficina", "taller"], demand: 1,
    desc: "Buscás entender las leyes del universo o desarrollar la matemática que se usa en todo: tecnología, finanzas, ciencia.",
    dia: "Resolver problemas, programar modelos, investigar, enseñar o trabajar en empresas de tecnología y finanzas.",
    materias: ["Cálculo", "Álgebra", "Física", "Programación", "Probabilidad"],
    salida: "Buena: cada vez más empresas de tecnología y datos contratan matemáticos y físicos.",
    ojo: "Es muy abstracta; solo si realmente disfrutás la matemática.",
    uy: "UdelaR – Facultad de Ciencias.",
    ar: "UBA (Exactas), UNLP, UNC e Instituto Balseiro (física).",
  },
  {
    id: "ambiental", name: "Gestión / Ciencias ambientales", code: "IRS",
    fields: ["naturaleza", "ciencia", "sociedad"], skills: ["ciencias", "orden", "oratoria"],
    dur: "4 años", durNum: 4, type: "Universitaria",
    math: 2, people: 1, sangre: false, env: ["aire", "oficina"], demand: 1,
    desc: "Trabajás para proteger el medio ambiente: estudiás la contaminación, los recursos naturales y cómo reducir el impacto humano.",
    dia: "Hacer estudios de impacto ambiental, monitorear agua y suelos, asesorar empresas o gobiernos, educar en sustentabilidad.",
    materias: ["Ecología", "Química ambiental", "Gestión de residuos", "Legislación ambiental", "Sistemas de información geográfica"],
    salida: "En crecimiento por las exigencias ambientales a las empresas.",
    ojo: "Combina ciencia con trámites y normativas.",
    uy: "UdelaR – Licenciatura en Gestión Ambiental (CURE, en el este del país).",
    ar: "UBA (Ciencias Ambientales), UNSAM, UNLP y otras.",
  },
  {
    id: "criminalistica", name: "Criminalística / Criminología", code: "ISR",
    fields: ["sociedad", "ciencia"], skills: ["ciencias", "orden", "escritura"],
    dur: "4 años", durNum: 4, type: "Universitaria",
    math: 2, people: 1, sangre: true, env: ["taller", "aire"], demand: 0,
    desc: "Investigás delitos con métodos científicos (huellas, rastros, pericias) o estudiás por qué ocurren.",
    dia: "Trabajar en escenas del crimen, laboratorios de pericias, juzgados o fuerzas de seguridad.",
    materias: ["Química", "Balística", "Dactiloscopía", "Derecho penal", "Criminología"],
    salida: "Limitada: casi todo el trabajo está en el Estado (policía, poder judicial).",
    ojo: "No es como en las series: es mucho trabajo de laboratorio e informes.",
    uy: "Opciones limitadas: consultá en la Escuela Nacional de Policía; otra vía es estudiar Química o Medicina y especializarte en lo forense.",
    ar: "IUPFA (Instituto Universitario de la Policía Federal) y universidades nacionales y privadas.",
  },

  // ===== Tecnología =====
  {
    id: "computacion", name: "Ingeniería en Computación / Sistemas", code: "IRC",
    fields: ["tecnologia"], skills: ["compu", "numeros", "orden"],
    dur: "5 años", durNum: 5, type: "Universitaria",
    math: 3, people: 0, sangre: false, env: ["oficina"], demand: 2,
    desc: "Diseñás y construís software, sistemas y redes: apps, páginas web, sistemas de bancos, inteligencia artificial.",
    dia: "Programar, diseñar sistemas y resolver problemas técnicos en equipo, muchas veces desde casa.",
    materias: ["Programación", "Cálculo", "Álgebra", "Bases de datos", "Redes", "Sistemas operativos"],
    salida: "Excelente: de las áreas con más demanda y mejores sueldos, incluso trabajando para el exterior.",
    ojo: "Los primeros años tienen mucha matemática; mucha gente consigue trabajo antes de recibirse.",
    uy: "UdelaR – Facultad de Ingeniería; UTEC; ORT, UCU y UM (privadas).",
    ar: "UTN (Ingeniería en Sistemas), UBA, UNLP y otras; también privadas.",
  },
  {
    id: "programacion", name: "Programación / Desarrollo de software (carrera corta)", code: "IRC",
    fields: ["tecnologia"], skills: ["compu", "orden", "creatividad"],
    dur: "1 a 3 años", durNum: 2, type: "Tecnicatura / curso",
    math: 1, people: 0, sangre: false, env: ["oficina"], demand: 2,
    desc: "Aprendés a programar para crear páginas web, apps y sistemas, con una formación práctica y rápida.",
    dia: "Escribir y probar código, arreglar errores y trabajar en equipo con otros programadores y diseñadores.",
    materias: ["Lógica de programación", "Desarrollo web", "Bases de datos", "Inglés técnico", "Testing"],
    salida: "Muy buena para empezar a trabajar rápido; después podés seguir estudiando.",
    ojo: "Hay que actualizarse siempre: las tecnologías cambian rápido.",
    uy: "Jóvenes a Programar (gratuito, Plan Ceibal); UTU; UTEC; Analista Programador en ORT.",
    ar: "Tecnicaturas en UTN y universidades nacionales; cursos y bootcamps.",
  },
  {
    id: "datos", name: "Ciencia de datos / Estadística", code: "ICR",
    fields: ["tecnologia", "ciencia", "negocios"], skills: ["numeros", "compu", "orden"],
    dur: "4 años", durNum: 4, type: "Universitaria",
    math: 3, people: 0, sangre: false, env: ["oficina"], demand: 2,
    desc: "Analizás grandes cantidades de datos para encontrar patrones y ayudar a tomar decisiones.",
    dia: "Limpiar y analizar datos, armar gráficos y modelos predictivos y presentar conclusiones a otros equipos.",
    materias: ["Estadística", "Probabilidad", "Programación (Python, R)", "Bases de datos", "Aprendizaje automático"],
    salida: "Excelente y en crecimiento.",
    ojo: "Necesitás que te guste de verdad la matemática y la estadística.",
    uy: "UdelaR – Licenciatura en Estadística (FCEA); en ORT y UCU hay carreras y cursos de datos.",
    ar: "UBA (Licenciatura en Ciencias de Datos), UNR (Estadística) y otras.",
  },
  {
    id: "ux", name: "Diseño UX/UI (apps y webs)", code: "AIS",
    fields: ["tecnologia", "arte"], skills: ["visual", "creatividad", "compu", "empatia"],
    dur: "6 meses a 3 años", durNum: 2, type: "Curso / tecnicatura",
    math: 0, people: 1, sangre: false, env: ["oficina"], demand: 2,
    desc: "Diseñás cómo se ven y cómo se usan las apps y las páginas web, para que sean fáciles y lindas de usar.",
    dia: "Investigar a los usuarios, diseñar pantallas en Figma, hacer prototipos y probarlos con gente real.",
    materias: ["Diseño de interfaces", "Investigación de usuarios", "Prototipado", "Accesibilidad", "Diseño visual"],
    salida: "Muy buena, con muchas posibilidades de trabajo remoto.",
    ojo: "Pesa más el portfolio que el título: hay que mostrar proyectos.",
    uy: "ORT y otros institutos; cursos cortos online.",
    ar: "Cursos y diplomaturas en universidades e institutos; también como especialización de Diseño Gráfico.",
  },
  {
    id: "videojuegos", name: "Videojuegos y animación", code: "AIR",
    fields: ["tecnologia", "arte", "escena"], skills: ["compu", "creatividad", "visual"],
    dur: "2 a 4 años", durNum: 3, type: "Tecnicatura / licenciatura",
    math: 2, people: 0, sangre: false, env: ["oficina", "taller"], demand: 1,
    desc: "Creás videojuegos o animaciones: personajes, mundos, historias y la programación que los hace funcionar.",
    dia: "Modelar en 3D, animar, programar mecánicas de juego, diseñar niveles y probar el juego en equipo.",
    materias: ["Programación", "Modelado 3D", "Animación", "Diseño de juegos", "Guion"],
    salida: "Media: es un sector competitivo, pero hay estudios que trabajan para todo el mundo.",
    ojo: "Hay que armar portfolio y suele haber épocas de mucha presión antes de un lanzamiento.",
    uy: "ORT (Licenciatura en Animación y Videojuegos); cursos especializados.",
    ar: "Image Campus y otras escuelas; tecnicaturas en universidades.",
  },
  {
    id: "ciberseguridad", name: "Ciberseguridad", code: "IRC",
    fields: ["tecnologia"], skills: ["compu", "orden", "numeros"],
    dur: "2 a 4 años", durNum: 3, type: "Tecnicatura / especialización",
    math: 2, people: 0, sangre: false, env: ["oficina"], demand: 2,
    desc: "Protegés sistemas, redes y datos de ataques informáticos.",
    dia: "Buscar vulnerabilidades, monitorear redes, responder a incidentes y capacitar a otras personas.",
    materias: ["Redes", "Sistemas operativos", "Criptografía", "Programación", "Seguridad informática"],
    salida: "Excelente: faltan especialistas en todo el mundo.",
    ojo: "Se suele llegar desde sistemas o redes; requiere actualizarse todo el tiempo.",
    uy: "ORT y UTEC; también como especialización después de Ingeniería en Computación.",
    ar: "Tecnicaturas y licenciaturas en UTN y otras universidades.",
  },

  // ===== Ingeniería y construcción =====
  {
    id: "civil", name: "Ingeniería civil", code: "RIC",
    fields: ["construccion"], skills: ["numeros", "orden", "liderazgo"],
    dur: "5 a 6 años", durNum: 5, type: "Universitaria",
    math: 3, people: 1, sangre: false, env: ["aire", "oficina"], demand: 2,
    desc: "Diseñás y construís obras: edificios, puentes, rutas, puertos y redes de agua.",
    dia: "Calcular estructuras, dirigir obras, controlar presupuestos y coordinar equipos.",
    materias: ["Cálculo", "Física", "Estructuras", "Hidráulica", "Materiales"],
    salida: "Muy buena, ligada a la actividad de la construcción.",
    ojo: "Mucha matemática y física; parte del trabajo es en obra, al aire libre.",
    uy: "UdelaR – Facultad de Ingeniería; UM y UCU (privadas).",
    ar: "UTN, UBA, UNLP, UNC y otras.",
  },
  {
    id: "industrial", name: "Ingeniería industrial", code: "IEC",
    fields: ["construccion", "negocios"], skills: ["numeros", "liderazgo", "orden"],
    dur: "5 años", durNum: 5, type: "Universitaria",
    math: 3, people: 1, sangre: false, env: ["oficina", "taller"], demand: 2,
    desc: "Mejorás cómo funcionan empresas y fábricas: procesos, costos, calidad y logística.",
    dia: "Analizar procesos, coordinar la producción, gestionar proyectos y equipos, optimizar costos.",
    materias: ["Cálculo", "Física", "Investigación operativa", "Gestión de la producción", "Costos"],
    salida: "Excelente; es de las ingenierías más versátiles.",
    ojo: "Como todas las ingenierías, los primeros años tienen mucha matemática.",
    uy: "UdelaR – Facultad de Ingeniería; UCU y UM (privadas).",
    ar: "UTN, UBA, ITBA y otras.",
  },
  {
    id: "mecanica", name: "Ingeniería mecánica / eléctrica / mecatrónica", code: "RIC",
    fields: ["construccion", "tecnologia"], skills: ["numeros", "manual", "compu"],
    dur: "5 años", durNum: 5, type: "Universitaria",
    math: 3, people: 0, sangre: false, env: ["taller", "oficina"], demand: 2,
    desc: "Diseñás máquinas, motores, robots, instalaciones eléctricas y sistemas de energía.",
    dia: "Diseñar con software, supervisar mantenimiento en plantas industriales o trabajar en proyectos de energía renovable.",
    materias: ["Cálculo", "Física", "Termodinámica", "Electrotecnia", "Mecánica"],
    salida: "Muy buena en la industria y la energía.",
    ojo: "Muy exigente en física y matemática.",
    uy: "UdelaR – Facultad de Ingeniería; UTEC (Mecatrónica, Energías Renovables); ORT (Electrónica).",
    ar: "UTN, UBA, UNLP, UNC y otras.",
  },
  {
    id: "alimentos", name: "Ingeniería química / de alimentos", code: "IRC",
    fields: ["ciencia", "construccion", "gastro"], skills: ["ciencias", "numeros", "orden"],
    dur: "5 años", durNum: 5, type: "Universitaria",
    math: 3, people: 0, sangre: false, env: ["taller"], demand: 1,
    desc: "Diseñás procesos para fabricar a gran escala alimentos, bebidas, combustibles o productos químicos.",
    dia: "Trabajar en plantas industriales, controlar la calidad y desarrollar productos nuevos.",
    materias: ["Química", "Cálculo", "Operaciones unitarias", "Microbiología de alimentos", "Termodinámica"],
    salida: "Buena en la industria alimentaria y química.",
    ojo: "Combina química pesada con matemática pesada.",
    uy: "UdelaR – Facultad de Química e Ingeniería; UCU (Ingeniería en Alimentos).",
    ar: "UTN, UBA, UNL y otras.",
  },
  {
    id: "arquitectura", name: "Arquitectura", code: "AIR",
    fields: ["construccion", "arte"], skills: ["visual", "creatividad", "numeros"],
    dur: "5 a 6 años", durNum: 6, type: "Universitaria",
    math: 2, people: 1, sangre: false, env: ["oficina", "aire"], demand: 1,
    desc: "Diseñás espacios para vivir y trabajar: casas, edificios, plazas, interiores.",
    dia: "Hacer planos y modelos 3D, reunirte con clientes, visitar obras y presentar proyectos.",
    materias: ["Proyecto (taller de diseño)", "Dibujo", "Estructuras", "Historia de la arquitectura", "Construcción"],
    salida: "Media: depende mucho de la construcción; muchos trabajan de forma independiente.",
    ojo: "Las entregas implican noches sin dormir y bastante gasto en materiales.",
    uy: "UdelaR – FADU; ORT (privada).",
    ar: "UBA (FADU), UNLP, UNC y otras; también privadas.",
  },
  {
    id: "agronomia", name: "Agronomía", code: "RIE",
    fields: ["naturaleza"], skills: ["ciencias", "manual", "liderazgo"],
    dur: "5 años", durNum: 5, type: "Universitaria",
    math: 2, people: 1, sangre: false, env: ["aire"], demand: 2,
    desc: "Trabajás en la producción agropecuaria (cultivos, suelos, ganadería) cuidando el ambiente.",
    dia: "Recorrer campos, asesorar productores, analizar suelos o trabajar en empresas agrícolas.",
    materias: ["Química", "Botánica", "Suelos", "Producción vegetal", "Economía agraria"],
    salida: "Muy buena en países agroexportadores como Uruguay y Argentina.",
    ojo: "Mucho trabajo en el interior y al aire libre.",
    uy: "UdelaR – Facultad de Agronomía.",
    ar: "UBA (FAUBA), UNLP, UNC, UNR y otras.",
  },
  {
    id: "oficios", name: "Carreras técnicas (electricidad, mecánica, refrigeración)", code: "RCI",
    fields: ["construccion", "tecnologia"], skills: ["manual", "orden"],
    dur: "6 meses a 3 años", durNum: 2, type: "Técnica / curso",
    math: 1, people: 1, sangre: false, env: ["taller", "aire"], demand: 2,
    desc: "Aprendés un oficio técnico con mucha práctica y salida laboral rápida.",
    dia: "Instalar, reparar y mantener instalaciones eléctricas, motores o equipos.",
    materias: ["Electricidad", "Mecánica", "Dibujo técnico", "Seguridad", "Práctica de taller"],
    salida: "Muy buena: hay demanda de técnicos y muchos trabajan por su cuenta.",
    ojo: "Es trabajo físico y a veces en lugares incómodos.",
    uy: "UTU (gratuita, con cursos en todo el país).",
    ar: "Escuelas técnicas y centros de formación profesional (muchos gratuitos).",
  },

  // ===== Arte y diseño =====
  {
    id: "grafico", name: "Diseño gráfico / Comunicación visual", code: "AER",
    fields: ["arte", "comunicacion"], skills: ["visual", "creatividad", "compu"],
    dur: "3 a 4 años", durNum: 4, type: "Universitaria / terciaria",
    math: 0, people: 1, sangre: false, env: ["oficina", "taller"], demand: 1,
    desc: "Creás la parte visual de marcas, publicidades, libros, redes sociales y páginas web.",
    dia: "Diseñar logos, piezas para redes, carteles y packaging; reunirte con clientes y corregir propuestas.",
    materias: ["Tipografía", "Color", "Diseño editorial", "Ilustración", "Programas de diseño (Illustrator, Photoshop, Figma)"],
    salida: "Media: hay mucha competencia, pero un buen portfolio abre puertas (también con clientes del exterior).",
    ojo: "Los clientes piden muchos cambios: hay que tener paciencia y aceptar críticas.",
    uy: "UdelaR – FADU (Diseño de Comunicación Visual); ORT; UTU.",
    ar: "UBA (FADU), UNLP y otras; también privadas.",
  },
  {
    id: "moda", name: "Diseño de moda / indumentaria", code: "AER",
    fields: ["arte"], skills: ["visual", "creatividad", "manual"],
    dur: "3 a 4 años", durNum: 4, type: "Universitaria / terciaria",
    math: 0, people: 1, sangre: false, env: ["taller"], demand: 0,
    desc: "Diseñás ropa y accesorios: desde la idea y el dibujo hasta la moldería y la confección.",
    dia: "Investigar tendencias, dibujar colecciones, elegir telas, hacer moldes y producir para una marca o la tuya.",
    materias: ["Dibujo de figurín", "Moldería", "Textiles", "Historia de la moda", "Producción"],
    salida: "Variable: muchos emprenden su propia marca.",
    ojo: "Es un mundo competitivo; conviene sumar conocimientos de marketing y negocios.",
    uy: "UdelaR – FADU (Diseño Industrial, perfil Textil-Indumentaria); institutos privados.",
    ar: "UBA (FADU, Diseño de Indumentaria y Textil) y otras.",
  },
  {
    id: "interiores", name: "Diseño de interiores", code: "AER",
    fields: ["arte", "construccion"], skills: ["visual", "creatividad", "orden"],
    dur: "2 a 4 años", durNum: 3, type: "Terciaria",
    math: 1, people: 1, sangre: false, env: ["oficina", "taller"], demand: 1,
    desc: "Diseñás cómo se ven y funcionan los espacios por dentro: casas, locales, oficinas.",
    dia: "Medir espacios, elegir materiales, muebles y colores, hacer renders 3D y coordinar con obreros y proveedores.",
    materias: ["Dibujo técnico", "Diseño de espacios", "Materiales", "Iluminación", "Software 3D"],
    salida: "Media; muchos trabajan de forma independiente.",
    ojo: "Tenés que manejar presupuestos y clientes exigentes.",
    uy: "UTU e institutos privados.",
    ar: "Terciarios e institutos; algunas universidades privadas.",
  },
  {
    id: "disenoindustrial", name: "Diseño industrial / de producto", code: "ARI",
    fields: ["arte", "construccion", "tecnologia"], skills: ["visual", "manual", "creatividad"],
    dur: "4 a 5 años", durNum: 4, type: "Universitaria",
    math: 2, people: 1, sangre: false, env: ["taller", "oficina"], demand: 1,
    desc: "Diseñás objetos que se fabrican en serie: muebles, electrodomésticos, envases, productos.",
    dia: "Bocetar, modelar en 3D, hacer prototipos y trabajar con ingenieros y fábricas.",
    materias: ["Morfología", "Tecnología de materiales", "Modelado 3D", "Ergonomía", "Procesos productivos"],
    salida: "Media; mejor si lo combinás con tecnología o emprendimiento.",
    ojo: "Mezcla arte con bastante técnica.",
    uy: "UdelaR – FADU (Diseño Industrial).",
    ar: "UBA (FADU), UNLP, UNC y otras.",
  },
  {
    id: "bellasartes", name: "Artes visuales / Bellas artes", code: "AIR",
    fields: ["arte"], skills: ["visual", "creatividad", "manual"],
    dur: "4 a 5 años", durNum: 4, type: "Universitaria",
    math: 0, people: 0, sangre: false, env: ["taller"], demand: 0,
    desc: "Te formás como artista: pintura, escultura, grabado, fotografía, arte digital, instalaciones.",
    dia: "Producir obra en tu taller, exponer, dar clases, trabajar en museos, en gestión cultural o en ilustración.",
    materias: ["Dibujo", "Pintura", "Escultura", "Historia del arte", "Proyecto artístico"],
    salida: "Es difícil vivir solo del arte; muchos lo combinan con docencia, ilustración o gestión cultural.",
    ojo: "Necesitás mucha constancia y tolerancia a la incertidumbre económica.",
    uy: "UdelaR – Facultad de Artes (ex Escuela Nacional de Bellas Artes).",
    ar: "UNA (Universidad Nacional de las Artes), UNLP (Facultad de Artes) y escuelas de bellas artes provinciales.",
  },
  {
    id: "fotografia", name: "Fotografía", code: "ARE",
    fields: ["arte", "comunicacion"], skills: ["visual", "creatividad", "compu"],
    dur: "1 a 3 años", durNum: 2, type: "Curso / terciaria",
    math: 0, people: 1, sangre: false, env: ["taller", "aire"], demand: 0,
    desc: "Contás historias con imágenes: retratos, moda, eventos, productos, periodismo, naturaleza.",
    dia: "Planificar sesiones, sacar fotos, editar en Lightroom o Photoshop y conseguir clientes.",
    materias: ["Técnica fotográfica", "Iluminación", "Edición digital", "Composición", "Fotoperiodismo"],
    salida: "Variable: la mayoría trabaja freelance; las redes y los eventos dan bastante trabajo.",
    ojo: "El equipo es caro y tenés que saber venderte.",
    uy: "Foto Club Uruguayo, escuelas privadas y cursos.",
    ar: "Escuelas de fotografía (por ejemplo, Escuela Argentina de Fotografía), terciarios y cursos.",
  },
  {
    id: "estetica", name: "Cosmetología / Maquillaje / Estética", code: "ASR",
    fields: ["arte", "salud"], skills: ["manual", "empatia", "creatividad"],
    dur: "6 meses a 2 años", durNum: 1, type: "Curso",
    math: 0, people: 2, sangre: false, env: ["taller"], demand: 1,
    desc: "Trabajás con la imagen y el cuidado de la piel: maquillaje y tratamientos faciales y corporales.",
    dia: "Atender clientes, hacer tratamientos y maquillar para eventos o producciones.",
    materias: ["Cosmetología", "Anatomía de la piel", "Maquillaje", "Higiene", "Atención al cliente"],
    salida: "Buena, sobre todo emprendiendo o trabajando con redes sociales.",
    ojo: "Trabajo de pie y con los horarios de los clientes.",
    uy: "UTU e institutos privados.",
    ar: "Institutos y cursos (algunos con habilitación provincial).",
  },

  // ===== Música, escena y audiovisual =====
  {
    id: "musica", name: "Música / Producción musical", code: "AES",
    fields: ["escena"], skills: ["creatividad", "compu", "orden"],
    dur: "3 a 5 años", durNum: 4, type: "Universitaria / conservatorio",
    math: 1, people: 1, sangre: false, env: ["taller"], demand: 0,
    desc: "Te formás como intérprete, compositor/a, productor/a o docente de música.",
    dia: "Ensayar, tocar en vivo, componer, grabar y producir en estudio, dar clases.",
    materias: ["Lenguaje musical", "Instrumento", "Armonía", "Producción y grabación", "Historia de la música"],
    salida: "Variable; muchos lo combinan con docencia o producción para publicidad y audiovisual.",
    ojo: "Requiere muchísimas horas de práctica, desde antes de entrar.",
    uy: "UdelaR (Escuela Universitaria de Música) y escuelas de producción musical.",
    ar: "UNA (Artes Musicales), conservatorios provinciales y municipales, escuelas de producción musical.",
  },
  {
    id: "teatro", name: "Actuación / Teatro", code: "AES",
    fields: ["escena"], skills: ["oratoria", "creatividad", "empatia"],
    dur: "3 a 4 años", durNum: 3, type: "Escuela / terciaria",
    math: 0, people: 2, sangre: false, env: ["taller"], demand: 0,
    desc: "Te formás para actuar en teatro, cine, TV y publicidad, y también para dirigir o enseñar.",
    dia: "Ensayar, entrenar la voz y el cuerpo, ir a castings, actuar en obras o rodajes y dar talleres.",
    materias: ["Actuación", "Voz", "Expresión corporal", "Dramaturgia", "Historia del teatro"],
    salida: "Difícil y muy competitiva; muchos la combinan con docencia o locución.",
    ojo: "Necesitás tolerancia al rechazo (castings) y horarios nocturnos.",
    uy: "EMAD (Escuela Municipal de Arte Dramático) y escuelas de teatro privadas.",
    ar: "UNA (Artes Dramáticas), EMAD (CABA) y escuelas de teatro.",
  },
  {
    id: "cine", name: "Cine / Comunicación audiovisual", code: "AEI",
    fields: ["escena", "comunicacion", "arte"], skills: ["creatividad", "visual", "compu", "liderazgo"],
    dur: "3 a 4 años", durNum: 3, type: "Universitaria / terciaria",
    math: 0, people: 2, sangre: false, env: ["taller", "aire"], demand: 1,
    desc: "Hacés películas, series, publicidades y contenido audiovisual: dirección, guion, cámara, edición, sonido.",
    dia: "Escribir guiones, filmar, editar, coordinar rodajes con equipos grandes y hacer contenido para marcas.",
    materias: ["Guion", "Dirección", "Fotografía y cámara", "Montaje", "Sonido"],
    salida: "Media: la publicidad y el contenido digital dan mucho trabajo.",
    ojo: "Los rodajes tienen jornadas muy largas.",
    uy: "ECU (Escuela de Cine del Uruguay); ORT y UCU (Comunicación audiovisual).",
    ar: "ENERC (escuela nacional de cine, gratuita), UBA (Diseño de Imagen y Sonido), FUC y otras.",
  },
  {
    id: "danza", name: "Danza", code: "ARS",
    fields: ["escena", "deporte"], skills: ["fisico", "creatividad"],
    dur: "3 a 6 años", durNum: 4, type: "Escuela / terciaria",
    math: 0, people: 1, sangre: false, env: ["taller"], demand: 0,
    desc: "Te formás como bailarín/a, coreógrafo/a o profesor/a de danza.",
    dia: "Entrenar varias horas por día, ensayar, presentarte en funciones y dar clases.",
    materias: ["Técnica clásica y contemporánea", "Anatomía", "Composición coreográfica", "Música"],
    salida: "Es difícil vivir solo de bailar; la docencia y la coreografía son grandes salidas.",
    ojo: "Exigencia física muy alta; ideal si ya bailás desde hace años.",
    uy: "Escuela Nacional de Danza (SODRE) y academias.",
    ar: "UNA (Artes del Movimiento), Instituto Superior de Arte del Teatro Colón y escuelas provinciales.",
  },

  // ===== Comunicación =====
  {
    id: "periodismo", name: "Comunicación / Periodismo", code: "AES",
    fields: ["comunicacion", "sociedad"], skills: ["escritura", "oratoria", "creatividad"],
    dur: "4 años", durNum: 4, type: "Universitaria",
    math: 0, people: 2, sangre: false, env: ["oficina", "aire"], demand: 1,
    desc: "Informás, contás historias y creás contenido para medios, marcas o instituciones.",
    dia: "Investigar y escribir notas, hacer entrevistas, conducir, producir contenido para redes o hacer comunicación de empresas.",
    materias: ["Redacción", "Teoría de la comunicación", "Producción audiovisual", "Comunicación digital", "Sociología"],
    salida: "Competitiva; la comunicación institucional y digital da más trabajo que los medios tradicionales.",
    ojo: "Hay que construir contactos y mostrar lo que hacés.",
    uy: "UdelaR – Facultad de Información y Comunicación (FIC); UCU, ORT y UM (privadas).",
    ar: "UBA (Ciencias de la Comunicación), UNLP (Periodismo), TEA y otras.",
  },
  {
    id: "marketing", name: "Marketing / Publicidad / Community manager", code: "EAC",
    fields: ["comunicacion", "negocios"], skills: ["creatividad", "oratoria", "compu"],
    dur: "1 a 4 años", durNum: 3, type: "Curso / terciaria / universitaria",
    math: 1, people: 2, sangre: false, env: ["oficina"], demand: 2,
    desc: "Hacés que la gente conozca y elija productos y marcas: campañas, redes sociales, publicidad, estrategia.",
    dia: "Crear campañas y contenidos, manejar redes, analizar métricas y trabajar con diseñadores y clientes.",
    materias: ["Marketing", "Comportamiento del consumidor", "Publicidad", "Marketing digital", "Estadística básica"],
    salida: "Muy buena, especialmente en marketing digital.",
    ojo: "Ritmo rápido y orientado a resultados (ventas, seguidores, métricas).",
    uy: "ORT, UCU y UM (licenciaturas); cursos cortos de community manager.",
    ar: "Universidades nacionales y privadas, y muchos cursos cortos.",
  },
  {
    id: "letras", name: "Letras / Edición / Escritura", code: "AIS",
    fields: ["comunicacion", "sociedad", "educacion"], skills: ["escritura", "creatividad"],
    dur: "4 a 5 años", durNum: 4, type: "Universitaria",
    math: 0, people: 0, sangre: false, env: ["oficina", "aula"], demand: 0,
    desc: "Estudiás la literatura y el lenguaje; podés trabajar escribiendo, corrigiendo, editando o enseñando.",
    dia: "Leer y analizar textos, corregir y editar libros, escribir contenido, enseñar o investigar.",
    materias: ["Literatura", "Lingüística", "Teoría literaria", "Gramática", "Edición"],
    salida: "Media: la docencia y la corrección o redacción de contenidos son las salidas más comunes.",
    ojo: "Muchísima lectura; ideal si los libros son lo tuyo.",
    uy: "UdelaR – Facultad de Humanidades (FHCE); profesorado de Literatura en el CFE.",
    ar: "UBA (Filosofía y Letras), UNLP, UNC y profesorados de Lengua y Literatura.",
  },
  {
    id: "traductorado", name: "Traductorado / Interpretación", code: "CAS",
    fields: ["comunicacion"], skills: ["idiomas", "escritura", "orden"],
    dur: "4 años", durNum: 4, type: "Universitaria",
    math: 0, people: 1, sangre: false, env: ["oficina"], demand: 1,
    desc: "Traducís textos o interpretás conversaciones entre idiomas: documentos legales, libros, series, conferencias.",
    dia: "Traducir documentos, subtitular, interpretar en reuniones y revisar textos, muchas veces de forma remota.",
    materias: ["Idioma extranjero", "Gramática", "Traducción jurídica", "Traducción literaria", "Terminología"],
    salida: "Media-buena: poder trabajar a distancia para el exterior es una gran ventaja.",
    ojo: "Necesitás un nivel muy alto del idioma desde antes de empezar.",
    uy: "UdelaR – Facultad de Derecho (Traductorado Público).",
    ar: "UBA (Traductorado Público, Facultad de Derecho), Lenguas Vivas y profesorados de idiomas.",
  },
  {
    id: "eventos", name: "Relaciones públicas / Organización de eventos", code: "ESA",
    fields: ["comunicacion", "negocios", "gastro"], skills: ["oratoria", "orden", "liderazgo"],
    dur: "2 a 4 años", durNum: 3, type: "Terciaria / universitaria",
    math: 0, people: 2, sangre: false, env: ["oficina", "aire"], demand: 1,
    desc: "Organizás eventos y cuidás la imagen y las relaciones de empresas o personas.",
    dia: "Planificar eventos, negociar con proveedores, coordinar equipos el día del evento y vincularte con prensa y clientes.",
    materias: ["Organización de eventos", "Comunicación institucional", "Protocolo", "Marketing", "Gestión"],
    salida: "Buena si tenés contactos y buena reputación.",
    ojo: "Trabajás cuando otros se divierten: noches y fines de semana.",
    uy: "Institutos y universidades privadas.",
    ar: "Terciarios, UADE y otras privadas.",
  },

  // ===== Negocios =====
  {
    id: "administracion", name: "Administración de empresas", code: "ECS",
    fields: ["negocios"], skills: ["liderazgo", "numeros", "orden"],
    dur: "4 a 5 años", durNum: 4, type: "Universitaria",
    math: 2, people: 2, sangre: false, env: ["oficina"], demand: 2,
    desc: "Aprendés a dirigir organizaciones: finanzas, personas, marketing y estrategia.",
    dia: "Planificar, coordinar equipos, analizar números y tomar decisiones, o gestionar tu propio emprendimiento.",
    materias: ["Contabilidad", "Economía", "Administración", "Marketing", "Finanzas"],
    salida: "Muy buena y muy amplia.",
    ojo: "Es amplia; conviene especializarte en algo después.",
    uy: "UdelaR – FCEA (Licenciatura en Administración); ORT, UCU y UM.",
    ar: "UBA (Ciencias Económicas), UNLP, UNC y muchas privadas.",
  },
  {
    id: "contador", name: "Contador/a público/a", code: "CEI",
    fields: ["negocios"], skills: ["numeros", "orden"],
    dur: "4 a 5 años", durNum: 5, type: "Universitaria",
    math: 2, people: 1, sangre: false, env: ["oficina"], demand: 2,
    desc: "Llevás las cuentas y los impuestos de personas y empresas, y analizás su situación financiera.",
    dia: "Hacer balances, liquidar impuestos y sueldos, auditar empresas y asesorar clientes.",
    materias: ["Contabilidad", "Derecho comercial", "Impuestos", "Matemática financiera", "Auditoría"],
    salida: "Excelente: toda empresa necesita un contador.",
    ojo: "Hay épocas del año con mucha presión (vencimientos de impuestos).",
    uy: "UdelaR – FCEA; ORT, UCU y UM.",
    ar: "UBA (Ciencias Económicas), UNLP, UNC y muchas privadas.",
  },
  {
    id: "economia", name: "Economía", code: "ICE",
    fields: ["negocios", "sociedad", "ciencia"], skills: ["numeros", "escritura"],
    dur: "4 a 5 años", durNum: 5, type: "Universitaria",
    math: 3, people: 0, sangre: false, env: ["oficina"], demand: 1,
    desc: "Estudiás cómo funcionan la producción, el consumo, los precios y el dinero en un país o una empresa.",
    dia: "Analizar datos y hacer informes y proyecciones para bancos, consultoras, el gobierno o empresas.",
    materias: ["Microeconomía", "Macroeconomía", "Matemática", "Estadística", "Econometría"],
    salida: "Buena en bancos, consultoras y el sector público.",
    ojo: "Tiene mucha más matemática de lo que la gente imagina.",
    uy: "UdelaR – FCEA; ORT, UCU y UM.",
    ar: "UBA, UNLP, UTDT y otras.",
  },
  {
    id: "rrhh", name: "Recursos humanos / Relaciones laborales", code: "SEC",
    fields: ["negocios", "mente"], skills: ["empatia", "oratoria", "orden"],
    dur: "3 a 4 años", durNum: 4, type: "Universitaria",
    math: 1, people: 2, sangre: false, env: ["oficina"], demand: 1,
    desc: "Te ocupás de las personas dentro de una empresa: selección, capacitación, clima laboral y sueldos.",
    dia: "Entrevistar candidatos, organizar capacitaciones, resolver conflictos y gestionar beneficios.",
    materias: ["Derecho laboral", "Psicología organizacional", "Gestión de personas", "Sociología del trabajo"],
    salida: "Buena en empresas medianas y grandes.",
    ojo: "A veces tenés que comunicar decisiones difíciles, como despidos.",
    uy: "UdelaR – Facultad de Derecho (Relaciones Laborales); UCU y ORT.",
    ar: "Universidades nacionales (Relaciones del Trabajo) y privadas.",
  },
  {
    id: "comex", name: "Comercio internacional / Logística", code: "ECS",
    fields: ["negocios"], skills: ["idiomas", "liderazgo", "orden"],
    dur: "2 a 4 años", durNum: 4, type: "Universitaria / terciaria",
    math: 2, people: 1, sangre: false, env: ["oficina"], demand: 1,
    desc: "Gestionás la compra y venta de productos entre países: importaciones, exportaciones, transporte y negociación.",
    dia: "Negociar con clientes y proveedores de otros países, coordinar envíos, hacer trámites aduaneros y calcular costos.",
    materias: ["Comercio exterior", "Logística", "Derecho aduanero", "Inglés", "Marketing internacional"],
    salida: "Buena, sobre todo si manejás inglés u otro idioma.",
    ojo: "Mucho trámite y papeleo.",
    uy: "ORT, UCU y UM; cursos de comercio exterior en UTU.",
    ar: "Universidades nacionales y privadas; terciarios.",
  },
  {
    id: "asistadmin", name: "Asistente administrativo/contable", code: "CES",
    fields: ["negocios"], skills: ["orden", "numeros", "compu"],
    dur: "1 a 2 años", durNum: 1, type: "Curso / técnica",
    math: 1, people: 1, sangre: false, env: ["oficina"], demand: 1,
    desc: "Hacés funcionar el día a día de una oficina: papeles, facturas, agendas y atención.",
    dia: "Facturar, archivar, manejar planillas de Excel y atender clientes y proveedores.",
    materias: ["Contabilidad básica", "Excel", "Gestión administrativa", "Redacción"],
    salida: "Buena para entrar a trabajar rápido.",
    ojo: "Es un trabajo rutinario; ideal si te gusta el orden.",
    uy: "UTU (cursos administrativos).",
    ar: "Centros de formación profesional y terciarios.",
  },

  // ===== Leyes y sociedad =====
  {
    id: "derecho", name: "Abogacía / Derecho", code: "ESI",
    fields: ["sociedad"], skills: ["oratoria", "escritura", "liderazgo"],
    dur: "5 a 6 años", durNum: 6, type: "Universitaria",
    math: 0, people: 2, sangre: false, env: ["oficina"], demand: 1,
    desc: "Conocés las leyes para defender, asesorar o representar a personas y empresas.",
    dia: "Redactar escritos y contratos, ir a audiencias, negociar acuerdos y asesorar clientes.",
    materias: ["Derecho civil", "Derecho penal", "Derecho constitucional", "Derecho comercial", "Derecho laboral"],
    salida: "Muy competitiva, pero con muchas especialidades y salidas (empresas, Estado, estudios jurídicos).",
    ojo: "Muchísima lectura y memoria.",
    uy: "UdelaR – Facultad de Derecho; UCU, UM, UDE y CLAEH.",
    ar: "UBA, UNLP, UNC y muchas privadas.",
  },
  {
    id: "escribania", name: "Escribanía / Notariado", code: "CES",
    fields: ["sociedad", "negocios"], skills: ["orden", "escritura"],
    dur: "5 a 6 años", durNum: 6, type: "Universitaria",
    math: 0, people: 1, sangre: false, env: ["oficina"], demand: 1,
    desc: "Das fe pública: redactás y certificás contratos, compraventas de casas, testamentos y poderes.",
    dia: "Redactar escrituras, revisar documentos, atender clientes y hacer trámites en registros.",
    materias: ["Derecho civil", "Derecho registral", "Derecho notarial", "Derecho comercial", "Derecho tributario"],
    salida: "Buena, aunque lleva tiempo armar clientela.",
    ojo: "Trabajo muy detallista: un error puede salir caro.",
    uy: "UdelaR – Facultad de Derecho; UCU y UM.",
    ar: "Universidades con Escribanía o Notariado (UBA, UNLP y otras).",
  },
  {
    id: "cpolitica", name: "Ciencia política / Relaciones internacionales", code: "EIS",
    fields: ["sociedad"], skills: ["escritura", "oratoria", "idiomas"],
    dur: "4 años", durNum: 4, type: "Universitaria",
    math: 1, people: 1, sangre: false, env: ["oficina"], demand: 0,
    desc: "Estudiás cómo funcionan el poder, los gobiernos y las relaciones entre países.",
    dia: "Analizar políticas públicas, asesorar en el Estado u organismos internacionales, investigar o trabajar en ONGs.",
    materias: ["Teoría política", "Sistemas políticos", "Historia", "Economía", "Derecho internacional"],
    salida: "Media: suele haber más trabajo en el Estado y en organismos.",
    ojo: "Pesan mucho los idiomas y los contactos.",
    uy: "UdelaR – Facultad de Ciencias Sociales; UCU y ORT.",
    ar: "UBA (Ciencias Sociales), UNSAM, UTDT y otras.",
  },
  {
    id: "trabajosocial", name: "Trabajo social", code: "SEA",
    fields: ["sociedad", "mente"], skills: ["empatia", "oratoria", "orden"],
    dur: "4 años", durNum: 4, type: "Universitaria",
    math: 0, people: 2, sangre: false, env: ["aire", "oficina"], demand: 1,
    desc: "Acompañás a personas y familias en situación de vulnerabilidad y trabajás para mejorar sus condiciones de vida.",
    dia: "Hacer entrevistas y visitas, coordinar con escuelas, centros de salud y juzgados, y diseñar programas sociales.",
    materias: ["Trabajo social", "Sociología", "Políticas sociales", "Psicología", "Derecho de familia"],
    salida: "Buena en el Estado, intendencias o municipios, ONGs y salud.",
    ojo: "Es emocionalmente duro: se trabaja con situaciones difíciles.",
    uy: "UdelaR – Facultad de Ciencias Sociales.",
    ar: "UBA, UNLP, UNC y otras nacionales.",
  },
  {
    id: "sociologia", name: "Sociología / Antropología", code: "ISA",
    fields: ["sociedad", "mente", "ciencia"], skills: ["escritura", "numeros"],
    dur: "4 años", durNum: 4, type: "Universitaria",
    math: 1, people: 1, sangre: false, env: ["oficina", "aire"], demand: 0,
    desc: "Investigás cómo se organizan y se comportan los grupos humanos y las culturas.",
    dia: "Diseñar encuestas, hacer entrevistas y trabajo de campo, analizar datos y escribir informes.",
    materias: ["Teoría social", "Metodología de la investigación", "Estadística", "Antropología", "Historia"],
    salida: "Media: consultoras de opinión pública, Estado, investigación y docencia.",
    ojo: "Muchas salidas requieren posgrado.",
    uy: "UdelaR – Facultad de Ciencias Sociales (Sociología) y FHCE (Antropología).",
    ar: "UBA y otras nacionales.",
  },
  {
    id: "historia", name: "Historia", code: "IAS",
    fields: ["sociedad", "educacion"], skills: ["escritura"],
    dur: "4 años", durNum: 4, type: "Universitaria / formación docente",
    math: 0, people: 1, sangre: false, env: ["aula", "oficina"], demand: 1,
    desc: "Investigás el pasado para entender el presente; la mayoría trabaja en docencia, archivos o museos.",
    dia: "Leer fuentes, investigar en archivos, escribir, enseñar o trabajar en museos y patrimonio.",
    materias: ["Historia antigua", "Historia americana", "Historia nacional", "Teoría de la historia"],
    salida: "La docencia es la salida principal.",
    ojo: "Muchísima lectura.",
    uy: "UdelaR – FHCE; profesorado de Historia en el CFE (IPA).",
    ar: "UBA (Filosofía y Letras), UNLP y profesorados de Historia.",
  },
  {
    id: "bibliotecologia", name: "Bibliotecología / Archivología", code: "CSI",
    fields: ["educacion", "sociedad", "comunicacion"], skills: ["orden", "compu"],
    dur: "4 años", durNum: 4, type: "Universitaria",
    math: 0, people: 1, sangre: false, env: ["oficina", "aula"], demand: 1,
    desc: "Organizás la información y facilitás el acceso a ella: libros, archivos, documentos digitales.",
    dia: "Catalogar, gestionar bases de datos, ayudar a las personas a encontrar información y digitalizar archivos.",
    materias: ["Catalogación", "Gestión de la información", "Archivística", "Tecnologías de la información"],
    salida: "Buena y con poca competencia.",
    ojo: "Trabajo tranquilo y metódico; ideal si eso te gusta.",
    uy: "UdelaR – Facultad de Información y Comunicación (FIC).",
    ar: "UBA (Filosofía y Letras) y otras nacionales.",
  },

  // ===== Educación =====
  {
    id: "maestra", name: "Magisterio (maestra/o de primaria)", code: "SAE",
    fields: ["educacion"], skills: ["empatia", "oratoria", "creatividad"],
    dur: "4 años", durNum: 4, type: "Formación docente",
    math: 1, people: 2, sangre: false, env: ["aula"], demand: 2,
    desc: "Enseñás a niños de 6 a 12 años todas las áreas básicas y acompañás su crecimiento.",
    dia: "Planificar clases, enseñar, corregir, acompañar a cada niño y hablar con las familias.",
    materias: ["Pedagogía", "Didáctica", "Psicología del desarrollo", "Matemática", "Lengua"],
    salida: "Muy buena: hay trabajo en todo el país y es un empleo estable.",
    ojo: "Grupos numerosos y mucha responsabilidad emocional.",
    uy: "CFE – Institutos Normales e Institutos de Formación Docente (públicos y gratuitos, en todo el país).",
    ar: "Institutos Superiores de Formación Docente (ISFD), públicos y gratuitos.",
  },
  {
    id: "profesorado", name: "Profesorado de secundaria", code: "SAI",
    fields: ["educacion"], skills: ["oratoria", "empatia", "escritura"],
    dur: "4 años", durNum: 4, type: "Formación docente",
    math: 1, people: 2, sangre: false, env: ["aula"], demand: 2,
    desc: "Enseñás tu materia favorita (biología, historia, inglés, matemática, literatura…) a adolescentes.",
    dia: "Dar clases en uno o varios liceos o colegios, planificar, corregir y acompañar a los estudiantes.",
    materias: ["La materia que elijas", "Pedagogía", "Didáctica", "Psicología del adolescente"],
    salida: "Muy buena; en matemática, física, química e inglés faltan muchos docentes.",
    ojo: "Muchas veces se trabaja en varios lugares a la vez.",
    uy: "CFE – IPA en Montevideo y Centros Regionales de Profesores (CeRP) en el interior.",
    ar: "ISFD y profesorados universitarios.",
  },
  {
    id: "inicial", name: "Educación inicial / primera infancia", code: "SAR",
    fields: ["educacion"], skills: ["empatia", "creatividad", "fisico"],
    dur: "4 años", durNum: 4, type: "Formación docente",
    math: 0, people: 2, sangre: false, env: ["aula"], demand: 2,
    desc: "Acompañás el desarrollo de niños pequeños (0 a 5 años) a través del juego y la estimulación.",
    dia: "Planificar juegos y actividades, cuidar, observar el desarrollo de cada niño y trabajar con las familias.",
    materias: ["Desarrollo infantil", "Didáctica del nivel inicial", "Juego", "Expresión plástica y musical"],
    salida: "Buena: jardines, centros CAIF y centros de primera infancia.",
    ojo: "Requiere mucha energía y paciencia todos los días.",
    uy: "CFE (Maestro/a de Primera Infancia) y cursos de educador/a en primera infancia.",
    ar: "ISFD (Profesorado de Educación Inicial).",
  },
  {
    id: "psicopedagogia", name: "Psicopedagogía", code: "SIA",
    fields: ["educacion", "mente"], skills: ["empatia", "orden", "escritura"],
    dur: "4 años", durNum: 4, type: "Universitaria",
    math: 0, people: 2, sangre: false, env: ["aula", "clinica"], demand: 1,
    desc: "Ayudás a niños, adolescentes y adultos que tienen dificultades para aprender.",
    dia: "Evaluar dificultades, hacer sesiones de tratamiento y orientar a docentes y familias.",
    materias: ["Psicología del aprendizaje", "Neuropsicología", "Evaluación psicopedagógica", "Didáctica"],
    salida: "Buena en colegios y consultorios.",
    ojo: "Los avances son lentos; requiere paciencia.",
    uy: "UCU (privada).",
    ar: "Universidades privadas y algunas nacionales; terciarios.",
  },
  {
    id: "edfisica", name: "Educación física", code: "SRE",
    fields: ["deporte", "educacion"], skills: ["fisico", "liderazgo", "empatia"],
    dur: "4 años", durNum: 4, type: "Universitaria / formación docente",
    math: 1, people: 2, sangre: false, env: ["aire", "aula"], demand: 2,
    desc: "Enseñás y promovés la actividad física y el deporte en escuelas, clubes y gimnasios.",
    dia: "Dar clases, entrenar equipos, planificar actividades recreativas y trabajar en campamentos y colonias.",
    materias: ["Anatomía", "Fisiología del ejercicio", "Deportes", "Recreación", "Pedagogía"],
    salida: "Muy buena: escuelas, liceos o colegios, clubes y gimnasios.",
    ojo: "Trabajo físico y mucho al aire libre.",
    uy: "UdelaR – ISEF (Instituto Superior de Educación Física); institutos privados.",
    ar: "ISFD de Educación Física y universidades nacionales.",
  },
  {
    id: "entrenador", name: "Entrenador/a personal / Instructor/a de fitness", code: "SRE",
    fields: ["deporte"], skills: ["fisico", "empatia", "liderazgo"],
    dur: "6 meses a 2 años", durNum: 1, type: "Curso",
    math: 0, people: 2, sangre: false, env: ["aire", "taller"], demand: 1,
    desc: "Diseñás rutinas y entrenás a personas para mejorar su salud y su rendimiento.",
    dia: "Dar clases grupales o personalizadas en gimnasios, al aire libre u online.",
    materias: ["Anatomía", "Entrenamiento", "Primeros auxilios", "Nutrición básica"],
    salida: "Buena, sobre todo si armás tu propia clientela o hacés contenido online.",
    ojo: "Horarios cortados (temprano a la mañana y de noche).",
    uy: "Institutos privados de formación de instructores.",
    ar: "Institutos y cursos de instructor.",
  },

  // ===== Gastronomía y turismo =====
  {
    id: "gastronomia", name: "Gastronomía / Chef / Pastelería", code: "ARE",
    fields: ["gastro"], skills: ["manual", "creatividad", "fisico"],
    dur: "1 a 3 años", durNum: 2, type: "Terciaria / curso",
    math: 1, people: 1, sangre: false, env: ["taller"], demand: 2,
    desc: "Creás y preparás comidas en restaurantes, hoteles, catering o tu propio emprendimiento.",
    dia: "Preparar platos, crear menús, manejar una cocina y controlar costos y calidad.",
    materias: ["Técnicas culinarias", "Pastelería", "Higiene y seguridad alimentaria", "Costos", "Cocina internacional"],
    salida: "Muy buena; también para emprender (catering, pastelería).",
    ojo: "Jornadas largas, de pie y los fines de semana.",
    uy: "UTU (cursos gratuitos de gastronomía); escuelas privadas como Gato Dumas.",
    ar: "Gato Dumas, IAG y muchos terciarios.",
  },
  {
    id: "turismo", name: "Turismo y hotelería", code: "ESC",
    fields: ["gastro", "negocios"], skills: ["idiomas", "oratoria", "orden"],
    dur: "2 a 4 años", durNum: 3, type: "Terciaria / universitaria",
    math: 1, people: 2, sangre: false, env: ["oficina", "aire"], demand: 1,
    desc: "Organizás y gestionás viajes, hoteles y experiencias turísticas.",
    dia: "Atender turistas, armar paquetes, gestionar hoteles o guiar recorridos.",
    materias: ["Geografía turística", "Gestión hotelera", "Idiomas", "Marketing turístico"],
    salida: "Buena en temporada; Uruguay y Argentina reciben mucho turismo.",
    ojo: "Depende de las temporadas y se trabaja cuando otros están de vacaciones.",
    uy: "UdelaR (Licenciatura en Turismo); UTU; institutos privados.",
    ar: "Universidades nacionales y privadas; terciarios.",
  },
];

// ---------------------------------------------------------------------------
// Plan de acción
// ---------------------------------------------------------------------------
const TRY_IT = {
  R: [
    "Hacé un curso corto y práctico (electricidad, carpintería, cocina, jardinería) para ver si disfrutás el trabajo con las manos.",
    "Pedile a algún conocido que trabaje en un taller, una obra o el campo que te deje acompañarlo un día.",
    "Armá o repará algo por tu cuenta: un mueble, una bici, una huerta.",
  ],
  I: [
    "Hacé gratis un curso introductorio en Khan Academy, Coursera o edX (en Coursera y edX podés hacer muchos cursos gratis, sin certificado).",
    "Buscá en YouTube clases de 1er año de la carrera que te interesa y mirá si te enganchan.",
    "Elegí una pregunta que te intrigue e investigala a fondo durante una semana.",
  ],
  A: [
    "Armá un mini portfolio con 5 trabajos tuyos (dibujos, fotos, diseños o videos).",
    "Hacé un taller corto de diseño, fotografía, teatro o música.",
    "Seguí a profesionales del área en Instagram o Behance y fijate cómo trabajan.",
  ],
  S: [
    "Sumate a un voluntariado: apoyo escolar, comedores, hogares de adultos mayores.",
    "Ofrecé clases particulares de alguna materia que te vaya bien.",
    "Pedí permiso para acompañar a un profesional de la salud o la educación durante un día.",
  ],
  E: [
    "Vendé algo (comida, ropa usada, un servicio) y llevá las cuentas de lo que ganás.",
    "Organizá un evento, una rifa o una actividad con amigos.",
    "Mirá entrevistas a emprendedores y anotá qué hacen en su día a día.",
  ],
  C: [
    "Hacé un curso de Excel (hay muchos gratis online).",
    "Ofrecete para ordenar las cuentas o el stock de un negocio familiar o de un conocido.",
    "Organizá un proyecto con cronograma y presupuesto, aunque sea un viaje con amigos.",
  ],
};

const COUNTRY_INFO = {
  uy: {
    name: "Uruguay",
    tips: [
      "Visitá la Expo Educa (la feria de carreras que se hace todos los años) y las jornadas de puertas abiertas de las facultades.",
      "La UdelaR tiene orientación vocacional gratuita a través de su Programa de Respaldo al Aprendizaje (PROGRESA).",
      "Si te interesa algo corto o técnico, mirá la oferta de UTU y UTEC: son públicas y gratuitas y tienen sedes en el interior.",
    ],
  },
  ar: {
    name: "Argentina",
    tips: [
      "Andá a la expo de carreras de tu ciudad y a las jornadas de puertas abiertas de las universidades.",
      "Muchas universidades nacionales (por ejemplo, la UBA) tienen orientación vocacional gratuita.",
      "Si te interesa algo corto o técnico, mirá las tecnicaturas de la UTN y los institutos terciarios de tu provincia.",
    ],
  },
  otro: {
    name: "tu país",
    tips: [
      "Buscá las ferias de carreras y las jornadas de puertas abiertas de las universidades de tu ciudad.",
      "Muchas universidades públicas ofrecen orientación vocacional gratuita: preguntá en la que te quede más cerca.",
      "Averiguá qué carreras cortas o técnicas públicas hay cerca tuyo: son una gran forma de empezar.",
    ],
  },
};

const INTERVIEW_QUESTIONS = [
  "¿Cómo es un día normal en tu trabajo?",
  "¿Qué es lo que menos te gusta de tu profesión?",
  "¿Cuánto tardaste de verdad en recibirte? ¿Qué materias te costaron más?",
  "¿Es fácil conseguir trabajo? ¿Cómo conseguiste el primero?",
  "Si tuvieras que elegir de nuevo, ¿volverías a estudiar lo mismo?",
];
